### ISSUE TITLE
Make automatic flipping of needle orientation optional

### ISSUE THREAD

**Issue by mholden8** [SlicerIGT/SlicerIGT#100]
When computing the pivot calibration or spin calibration, the automatic "flipping" of the needle should be made optional. This can be added as a parameter to the functions computing the pivot and spin calibrations (default behaviour should be to automatically flip).

Improve the documentation on this automatic flipping behaviour.

See discussion: https://github.com/SlicerIGT/SlicerIGT/commit/80106cce77376eb13399aa08d9da6ac862e8b532#commitcomment-19125336

**Comment by lassoan** [comment]
@mholden8 Are you planning to implement this?

**Comment by mholden8** [comment]
Yes, please see: https://github.com/mholden8/SlicerIGT/tree/auto-orient-pivot-spin-calibration. I asked @tavaughan to test it with his particular application before creating the pull request.

**Comment by tavaughan** [comment]
Seems to work in CathNav.

**Comment by mholden8** [comment]
Fixed in pull request #102.
