### ISSUE TITLE
MarkupsToModel crashes when reloading scene

### ISSUE THREAD

**Issue by tavaughan** [SlicerIGT/SlicerIGT#106]
Can be reproduced by doing the following:
1. Open Slicer
2. Open the MarkupsToModel widget
3. Save a scene
4. Close Slicer
5. Open Slicer
6. Open the MarkupsToModel widget
7. Load the scene

The crash does not happen if step 6 is skipped.

I do not know how to fix this.

**Comment by lassoan** [comment]
Problem fixed and module is moved to https://github.com/SlicerIGT/SlicerMarkupsToModel extension.
