### ISSUE TITLE
Transform Fusion - Move the Timed Update timer elsewhere

### ISSUE THREAD

**Issue by tavaughan** [SlicerIGT/SlicerIGT#107]
The timer doesn't belong in the widget, it would not work across multiple parameter nodes, updating multiple outputs

**Comment by tavaughan** [comment]
Now that there is a real "Automatic Update", this feature does not seem to have much practical use. The options I see are:
- leave it as-is.
- remove it completely and all the issues associated with it.

Probably removing it is not much work, and could save future trouble.

**Comment by lassoan** [comment]
What is this Timed Update timer?

**Comment by tavaughan** [comment]
It is a QTimer, and the transform fusion output is updated on timeout

**Comment by lassoan** [comment]
OK, if auto-update is now managed in the logic it's good and auto-update should be removed from GUI (and only manual update should be kept, the same way, preferably with the same checked button GUI as in MarkupsToModel).

**Comment by tavaughan** [comment]
My intention is to make it behave the same way as in other modules.

**Comment by tavaughan** [comment]
Timed update has been replaced with auto-update (event-based).

**Comment by tavaughan** [comment]
No wait, I lied. It's still there.
