### ISSUE TITLE
Offset around points is unpredictable

### ISSUE THREAD

**Issue by ungi** [SlicerIGT/SlicerIGT#121]
Probably a glyph is added around points, but it seems random to me. Attached two point sets. I cannot get rid of the offset around points in the "bad" one. The "good" one is very similar but no offset is created around points.

[Temp.zip](https://github.com/SlicerIGT/SlicerIGT/files/987309/Temp.zip)

**Comment by tavaughan** [comment]
I created a pull request. Once merged, please verify that the module behaves as expected.

**Comment by tavaughan** [comment]
@ungi Have you had a chance to try the fix yet?

**Comment by tavaughan** [comment]
@ungi Could you please verify that the problem is fixed?

**Comment by ungi** [comment]
I could not reproduce the issue. Thanks.
