### ISSUE TITLE
Simplify MarkupsToModel singular surface detection and compensation

### ISSUE THREAD

**Issue by lassoan** [SlicerIGT/SlicerIGT#125]
This is a follow-up on this pull request: https://github.com/SlicerIGT/SlicerIGT/pull/123#issuecomment-301540958

ComputePointArrangement, ComputePointRangeAlongAxis, ComputeSurfaceExtrusionAmount are way too complicated.
ComputeBestFitPlaneAxes should just always return all three axes as a vtkMatrix4x4 (x axis: largest variance; z axis: smallest variance). You then use this matrix to transform all points (transform polydata filter) to the bounding box coordinate system and get the extents (output->GetExtents).
If extentX<eps => singular;
else if extentY/extentX<eps => linear;
else if extentZ/sqrt(extentXextentX+extentYextent) < someThreshold => planar;
else nonplanar.
Extrusion amount: 1/100 of the norm of the bounding box extent. If extent is 0 then I think a fixed value is OK.

**Comment by tavaughan** [comment]
Thanks. I'll take a look when I get the chance.
