### ISSUE TITLE
BreachWarning and WatchDog sounds not playing (in Linux?)

### ISSUE THREAD

**Issue by tavaughan** [SlicerIGT/SlicerIGT#134]
To reproduce:

1. Create sphere model
2. Create an identity linear transform
3. Set up BreachWarning with the model and transform as inputs.
4. Check "Play Warning Sound"
5. (optional) Move the linear transform around - inside/outside the sphere

**Comment by lassoan** [comment]
Let's investigate it after Slicer switches to Qt5.

**Comment by tavaughan** [comment]
It works now.
