### ISSUE TITLE
Rename CollectFiducials to CollectPoints

### ISSUE THREAD

**Issue by tavaughan** [SlicerIGT/SlicerIGT#139]
Something to consider farther down the road, when collect fiducial collects nodes other than markups fiducials.

**Comment by tavaughan** [comment]
Please ignore referenced+deleted commit above (it was meant for issue 137). It seems as though there is currently no way to 'unreference' deleted commits on Github.

**Comment by tavaughan** [comment]
@lassoan Do we want to proceed with this rename?

**Comment by lassoan** [comment]
Yes
