### ISSUE TITLE
Output warning in fiducial registration wizard if point matching is ambiguous

### ISSUE THREAD

**Issue by tavaughan** [SlicerIGT/SlicerIGT#146]

**Comment by lassoan** [comment]
By "output" do you mean displaying a message on the GUI, logging a warning message, or providing an API for modules that use this module?

I think we already display residual error. Would this be somehow smarter than that?

**Comment by tavaughan** [comment]
Message on the GUI. Probably some API elements in the helper classes.

This warning would be for when there are two or more equally-good point-to-point mappings. Then it isn't clear which one is correct.

**Comment by lassoan** [comment]
OK, makes sense.
