### ISSUE TITLE
Rename Transform Fusion?

### ISSUE THREAD

**Issue by tavaughan** [SlicerIGT/SlicerIGT#152]
@lassoan We discussed renaming Transform Fusion to better reflect its new functionality. It can now concatenate transforms, and it can now separate translation or rotation information. Transform Processor (or something along those lines) was suggested in #44.

**Comment by lassoan** [comment]
Transform Processor sounds good to me!

**Comment by lassoan** [comment]
Can it also invert transforms?

**Comment by tavaughan** [comment]
@lassoan Indirectly. You would need to compute full transform from parent to child, and store the result in another transform.

I could add a convenience mode to take node that stores transform to parent, and create a new transform node that stores inverted transform to parent?
