### ISSUE TITLE
TransformProcessor - compute full transform ignores advanced settings to TransformProcessor

### ISSUE THREAD

**Issue by tavaughan** [SlicerIGT/SlicerIGT#172]

**Comment by tavaughan** [comment]
I think there is a case to be made that compute "full" transform shouldn't even have advanced options. It should just compute the "full" transform from one node to another. Advanced settings like omitting one of the dimensions in translation don't seem to make much sense, at least in my opinion and at this point in time.

**Comment by lassoan** [comment]
What are those advanced options?

**Comment by tavaughan** [comment]
@lassoan and I discussed a while back that we'll remove the advanced options for this TransformProcessor mode. If the options are needed later on the code can be updated accordingly.
