### ISSUE TITLE
Moving OpenIGTLinkRemote and PlusRemote to SlicerOpenIGTLink extension

### ISSUE THREAD

**Issue by lassoan** [SlicerIGT/SlicerIGT#173]
Now that OpenIGTLinkIF is in a Slicer extension, we could move OpenIGTLinkRemote and PlusRemote to that extension.
These modules only use OpenIGTLinkIF and don't rely on other SlicerIGT modules, so they more belong there.
Also, by moving them, we could remove dependency of SlicerIGT on OpenIGTLink, making building of SlicerIGT simpler and more robust (if SlicerOpenIGTLink fails to build, we can still have SlicerIGT).

See also https://github.com/openigtlink/SlicerOpenIGTLink/issues/24

**Comment by Sunderlandkyl** [comment]
This can be closed now.
