### ISSUE TITLE
Move CollectPoints to MarkupsToModel?

### ISSUE THREAD

**Issue by tavaughan** [SlicerIGT/SlicerIGT#182]
Its functionality seems to me a bit more relevant to MarkupsToModel. It would be practical too. Is CollectPoints used by many users of SlicerIGT?

**Comment by lassoan** [comment]
Most probably MarkupsToModel will be eventually merged into Slicer core (providing much needed curve and surface widgets), while collect points will not. So, I would not add anything to MarkupsToModel extension.

**Comment by tavaughan** [comment]
Ok
