### ISSUE TITLE
OpenIGTLink connection to an Atracsys fusionTrack500

### ISSUE THREAD

**Issue by dimitri80** [SlicerIGT/SlicerIGT#186]
Hello,
I am trying to connect an Atracsys fusionTrack500 tracker to 3D Slicer 4.10.0. so that I can create a  sequence metafile that tracks the StylusTip.
I successfully can start the Plus Server, and connect via OpenIGTLinkIF without error, but when I expand the Scene in my I/O Configuration, both IN and OUT are blank.  Below is my config file as well as error log, showing the connection.  Any help would be greatly appreciated. 

![slicer_error](https://user-images.githubusercontent.com/45240801/49527402-d0a7e800-f87f-11e8-9660-7bdf5141020e.jpg)
![slicer_ioconfig](https://user-images.githubusercontent.com/45240801/49527422-d7cef600-f87f-11e8-8b4a-b1d3b00befc9.jpg)
[atracsys.txt](https://github.com/SlicerIGT/SlicerIGT/files/2649594/atracsys.txt)

**Comment by dimitri80** [comment]
Hi, here is the log file for PLUS, I am not seeing any error, but i am very new to this system so I can be wrong.  Thank you for your expertise
[atracsys.txt](https://github.com/SlicerIGT/SlicerIGT/files/2650120/atracsys.txt)
.

**Comment by markasselin** [comment]
@dimitri80 Have you defined your marker ini file correctly?

**Comment by markasselin** [comment]
Since you're using passive markers only, set the ActiveMarkerPairingTimeSec to "0". And in you PlusOpenIGTLinkServer could you please set SendValidTransformsOnly to "FALSE". Alternatively, you can try increasing the MaxMeanRegistrationErrorMm attribute.

**Comment by dimitri80** [comment]
@markasselin
You nailed it, thank you.

**Comment by lassoan** [comment]
Great to see that it's solved. @markasselin could you please add a note about this to https://github.com/PlusToolkit/PlusLib/blob/master/src/Documentation/UserManual/DeviceAtracsys.dox to help future users find this useful tip more easily? Thanks!
