### ISSUE TITLE
‘ModelRegistrationLogic’ object has no attribute ‘delayDisplay’

### ISSUE THREAD

**Issue by sfglio** [SlicerIGT/SlicerIGT#203]

**Comment by sfglio** [comment]
#

**Comment by sfglio** [comment]
L185: delayDisplay('Running iterative closest point registration')

should be
L185: slicer.util.delayDisplay('Running iterative closest point registration')

**Comment by lassoan** [comment]
Thanks for reporting, we'll fix this in this and all other SlicerIGT modules.
