### ISSUE TITLE
ExampleGuidelet Missing

### ISSUE THREAD

**Issue by gibsoncw** [SlicerIGT/SlicerIGT#209]
Hi, I was trying to find the ExampleGuidelet file made for this 2016 workshop, but it seems it was taken off OpenIGT. Is it possible to add this again, or direct me to a repo where it can be downloaded?

https://www.na-mic.org/wiki/2016_Summer_Project_Week/Guidelets

https://github.com/SlicerIGT/SlicerIGT/tree/master/ExampleGuidelet

Thanks,
Chris

**Comment by Sunderlandkyl** [comment]
The example Guidelet was moved to its own repository here:
https://github.com/SlicerIGT/ExampleGuideletExtension/commits/master
