### ISSUE TITLE
Use the common simplified fiducial list widget in Fiducial registration wizard

### ISSUE THREAD

**Issue by lassoan** [SlicerIGT/SlicerIGT#23]
The fiducial widget is moved from Fiducial registration wizard to the Slicer core to make it usable for other modules, too.

Need to update the Fiducial registration wizard module to use this common implementation.

**Comment by cpinter** [comment]
Progress is tracked in the following repository:
https://subversion.assembla.com/svn/perklabsandbox/trunk/SimpleMarkupsWidget/

The final version will be committed to Slicer core in Modules/Markups/Widgets, and the PerkLabSandBox folder will be removed.

**Comment by tavaughan** [comment]
The Fiducial Registration Wizard module uses the qSlicerSimpleMarkupsWidget. Is this correct? Is the issue resolved?

**Comment by lassoan** [comment]
Yes, it's fixed now.
