### ISSUE TITLE
PlusRemote: live reconstruction fails

### ISSUE THREAD

**Issue by che85** [SlicerIGT/SlicerIGT#32]
```
Traceback (most recent call last):
  File "/Applications/Slicer 2.app/Contents/Extensions-24459/SlicerIGT/lib/Slicer-4.4/qt-scripted-modules/PlusRemote.py", line 776, in onStartStopLiveReconstructionButtonClicked
    self.onStartReconstruction()
  File "/Applications/Slicer 2.app/Contents/Extensions-24459/SlicerIGT/lib/Slicer-4.4/qt-scripted-modules/PlusRemote.py", line 931, in onStartReconstruction
    self.logic.startVolumeReconstuction(self.linkInputSelector.currentNode().GetID(), self.volumeReconstructorIDSelector.currentText, self.outputSpacingValue, self.outputOriginValue, self.outputExtentValue, self.printCommandResponse, self.getLiveReconstructionOutputFilename(), self.liveOutputVolumeDeviceBox.text)
  File "/Applications/Slicer 2.app/Contents/Extensions-24459/SlicerIGT/lib/Slicer-4.4/qt-scripted-modules/PlusRemote.py", line 1418, in startVolumeReconstuction
    self.cmdStartVolumeReconstruction.SetCommandAttribute('OutputSpacing', '%f %f %f' % tuple(outputSpacing))
TypeError: 'int' object is not iterable
```

**Comment by lassoan** [comment]
How did you get this error? Which Slicer version? Maybe you entered a single value where 3 values were expected?

**Comment by che85** [comment]
I think, that the problem is, that in onStartReconstruction, startVolumeReconstuction is called with parameter self.outputSpacingValue which is initialized with 0 in __init__

**Comment by che85** [comment]
Is a scout scan recording essential for creating a live reconstruction? 

When I first execute the scout scan, then it works as expected

**Comment by lassoan** [comment]
Yes, scout scan is needed. For live reconstruction you need to specify image position, orientation, spacing, and extent in advance. Probably the reconstruct button should be disabled if no scout scan is performed.

**Comment by che85** [comment]
Yes that makes sense. You also can think about running the scout scan shortly when for live reconstruction no ROI, Extent and Origin has been found.

**Comment by che85** [comment]
Since everything has been clarified, I will close this issue
