### ISSUE TITLE
Guidelet Class Design

### ISSUE THREAD

**Issue by che85** [SlicerIGT/SlicerIGT#33]
Hi,
I wonder why we are using a class hierarchy like the following:
![guideletloadablecurrent](https://cloud.githubusercontent.com/assets/10195822/8987045/017892c4-36ad-11e5-8656-23f8a8ad934f.png)

Instead of using one like:

![guideletloadableproposal](https://cloud.githubusercontent.com/assets/10195822/8986828/079f26aa-36ac-11e5-8b15-a1146ca8ff3e.png)

I mean all general GUI elements shall be implemented in GuideletWidget. All specific GUI elements shall be added by UltraSound which also could have its own logic class.  

I don't really see the need of a separate Guidelet class.

Maybe you can explain, why you designed it like that?

**Comment by lassoan** [comment]
GuideletWidget is the module widget that appears in the module docking window. Guidelet is a separate docking window. So, they are two separate widgets that can be nicely separated, so they should be in separate classes to have high cohesion and low coupling between classes.

**Comment by che85** [comment]
Ok I got it.

But what about the logic? It should belong the the Guidelet then and not to the GuideletWidget, right? Or is the GuideletLogic supposed to be used by both?

**Comment by lassoan** [comment]
The GuideletLogic is used by both widgets (Guidelet and GuideletWidget).
