### ISSUE TITLE
Enable convenience system for linking against SlicerIGT modules

### ISSUE THREAD

**Issue by franklinwk** [SlicerIGT/SlicerIGT#4]
Create a SlicerIGTConfig.cmake file that enables find_package(SlicerIGT) in other project for the creation of ${SlicerIGT_INCLUDE_DIRECTORIES} and ${SlicerIGT_LIBRARIES}

**Comment by jcfr** [comment]
Now that @lassoan added support for automatic generation of Config file for extension. This can be closed

**Comment by tavaughan** [comment]
Unless @lassoan has any objection, I'm marking this as closed.
