### ISSUE TITLE
Add module for combining and inverting transforms

### ISSUE THREAD

**Issue by lassoan** [SlicerIGT/SlicerIGT#44]
Often it is useful to have an inverted transform in the tree (for example, we receive ReferenceToTracker from OpenIGTLink but we would like to apply TrackerToReference transform to objects).

Also, it would be useful to be able to generate transforms by a sequence of concatenation/inversion.

The module could have a table where we define from/to coordinate system names for transforms (a heuristic can be used for obtaining that from the name of the transform) and another table that would contain computed transforms.

**Comment by tavaughan** [comment]
This functionality will be available in Transform Fusion.

**Comment by lassoan** [comment]
Great! Maybe then TransformFusion can be renamed to something like TransformProcessor or Process Transforms.

**Comment by tavaughan** [comment]
See Pull Request #142. If we want to rename the module, then can we create a new ticket?
