### ISSUE TITLE
Error closing scene when output transform present

### ISSUE THREAD

**Issue by lassoan** [SlicerIGT/SlicerIGT#55]
From @mholden8 

If the output transform is NULL, then the scene closes correctly. If the output transform is selected then Slicer crashes on "Close scene". Note that closing Slicer does not cause a crash, just closing the scene.

**Comment by tavaughan** [comment]
I cannot reproduce this issue. It may have been solved.

Steps I took:
1) Open Slicer
2) Navigate to Fiducial Registration Wizard
3) Create new "From" fiducial list
4) Create new "To" fiducial list
5) Create new Linear Transform or Transform for output
6) File -> Close Scene
I get no crash.
