### ISSUE TITLE
Ensure SlicerIGT modules follow needle orientation protocol

### ISSUE THREAD

**Issue by mholden8** [SlicerIGT/SlicerIGT#6]
After discussion with @franklinwk, we have agreed that we will follow the protocol of orienting the needle along the +Z axis (tip pointing in the -Z direction). For now, we will call the coordinate system the "ZShaft" coordinate system (indicating the shaft is along the +Z axis).

Please see the following issue for background information: PerkTutor/PerkTutor#2.

SlicerIGT modules should be modified so that they all follow the same needle orientation protocol.

**Comment by lassoan** [comment]
Implemented the change in PLUS. Needle coordinate system is now ZShaft, but not as defined as above (needle points to -Z direction) but as in OpenIGTLinkIF (needle points to +Z direction).
See: http://perk-software.cs.queensu.ca/plus/doc/nightly/user/ApplicationfCalCoordinateSystemDefinitions.html

Reason for +Z direction:
* points that are in front of the needle have positive coordinate values (e.g., a target 2cm away from the needle has a coordinate [0,0,2])
* compatibility with OpenIGTLinkIF locator model

**Comment by lassoan** [comment]
I've implemented the changes in Plus and CreateModels.
@mholden8 could you please update the spin calibration in Pivot calibration module to give the result in +ZShaft coordinate system?
