### ISSUE TITLE
Record orientation too (not just position)

### ISSUE THREAD

**Issue by lassoan** [SlicerIGT/SlicerIGT#65]
from @ungi 

It could be useful for showing oriented glyphs. Although currently the markups module does not orient glyphs based on orientation information.

**Comment by tavaughan** [comment]
Would the best approach be to generate glyphs from sequences? Then sequences could be recorded instead of markups?

**Comment by lassoan** [comment]
Yes, that's a good idea. Now that we have Sequences, we should retire CollectFiducials and have a module that creates a model (using glyphs) or fiducial list from a transform sequence (probably by selecting a transform node - which may be a regular transform node or a proxy node; and a sequence browser node; and maybe also some start/end frame).

**Comment by tavaughan** [comment]
Perhaps this should be marked as invalid?

**Comment by lassoan** [comment]
Agreed.
