### ISSUE TITLE
Add UI for surface normals filter

### ISSUE THREAD

**Issue by ungi** [SlicerIGT/SlicerIGT#7]
Surface models look much better if their normals are interpolated. This code makes nice surfaces in Slicer, but it would be good to be able to do it on the GUI:

n=slicer.util.getNode('manuntitled2')
nf=vtk.vtkPolyDataNormals()
nf.SetInput(n.GetPolyData())
nf.Update()
n.SetAndObservePolyData(nf.GetOutput())

**Comment by tavaughan** [comment]
This now seems to be a feature in the Models module of Slicer.
1) Create or load a model
2) Navigate to Models
3) Find the Lighting Category
4) Change Interpolation between Flat, Gouraud or Phong.
