### ISSUE TITLE
Make markups to modules module more robust

### ISSUE THREAD

**Issue by lassoan** [SlicerIGT/SlicerIGT#82]
Allow up to a certain percentage of points to be ignored.

User requirements:
- Include all the points (except the ones that are ignored) inside the surface
- Make the generated surface "smooth"
- Make the generated surface as small as possible (add minimum amount of extra space around the input points)

**Comment by tavaughan** [comment]
To clarify, points 2 and 3 are already addressed?

What is the criteria for determining the percentage of points to be ignored? What is the use case?

**Comment by lassoan** [comment]
Behavior is acceptable now and module is moved to https://github.com/SlicerIGT/SlicerMarkupsToModel extension.
